name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainer CLI
        run: npm install --location=global @devcontainers/cli
        env:
          NODE_OPTIONS: "--no-deprecation"

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Publish features
        run: |
          devcontainer features publish \
            --namespace "${{ github.repository_owner }}/devcontainer-features" \
            --oci-registry ghcr.io \
            src
        env:
          NODE_OPTIONS: "--no-deprecation"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
